spring:
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  application:
    name: activation-app

urls:
  activate: /activate

server:
  port: 8081
logging:
  level:
    root: DEBUG

management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /metrics
      exposure:
        include: ['prometheus']
  metrics:
    export:
      prometheus:
        enabled: true